=== adelelj2015/zathura/trunk/co.edu.usbcali.zathura.generator/config/zathura-generator-factory-config.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://lidis.usbcali.edu.co/schema/zathura-generator-factory-config"
    xmlns:tns="http://lidis.usbcali.edu.co/schema/zathura-generator-factory-config"
    elementFormDefault="qualified">
    <xsd:complexType name="TipoGenerator">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="gui-name" type="xsd:string"/>
            <xsd:element name="class" type="xsd:string"/>
            <xsd:element name="persistence" type="tns:persistenceType"/>
            <xsd:element name="logic" type="tns:logicType"/>
            <xsd:element name="view" type="tns:viewType"/>
            <xsd:element name="description" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="Tipo-zathura-generator">
        <xsd:sequence>
            <xsd:element name="generator" type="tns:TipoGenerator" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="zathura-generator" type="tns:Tipo-zathura-generator"/>

    <xsd:simpleType name="persistenceType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="jpa"/>
            <xsd:enumeration value="hibernateCore"/>
            <xsd:enumeration value="jdbc"/>
        </xsd:restriction>
    </xsd:simpleType>

     <xsd:simpleType name="logicType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="pojo"/>
            <xsd:enumeration value="spring"/>
            <xsd:enumeration value="guice"/>
        </xsd:restriction>
    </xsd:simpleType>

     <xsd:simpleType name="viewType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="icefaces"/>
            <xsd:enumeration value="primefaces"/>
            <xsd:enumeration value="gwt"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== adelelj2015/zathura/trunk/co.edu.usbcali.zathura.generator/config/zathura-generator-factory-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<zathura-generator  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns='http://lidis.usbcali.edu.co/schema/zathura-generator-factory-config'
   xsi:schemaLocation='http://lidis.usbcali.edu.co/schema/zathura-generator-factory-config zathura-generator-factory-config.xsd'>
   
	<generator>
		<name>ZathuraJavaEE_Web_Centric</name>
		<gui-name>IceFaces + JPA</gui-name>
		<class>co.edu.usbcali.lidis.zathura.generator.jee.jpa.webcentric.engine.ZathuraJavaEE_JPA_Web_Centric</class>
		<persistence>jpa</persistence>
		<logic>pojo</logic>
		<view>icefaces</view>
		<description>Icefaces,pojo,jpa</description>
	</generator>
	
	<generator>
		<name>ZathuraJavaEE_HibernateCore_Web_Centric</name>
		<gui-name>IceFaces + HibernateCore</gui-name>
		<class>com.vortexbird.amazilia.generator.jee.hibernatecore.webcentric.engine.ZathuraJavaEE_HibernateCore_Web_Centric</class>
		<persistence>hibernateCore</persistence>
		<logic>pojo</logic>
		<view>icefaces</view>
		<description></description>
	</generator>
	
	
	<generator>
		<name>ZathuraJavaEE_HibernateCore_Spring_Web_Centric</name>
		<gui-name>IceFaces + Hibernate Core + Spring</gui-name>
		<class>com.vortexbird.amazilia.generator.jee.hibernatecore.springcentric.engine.ZathuraJavaEE_HibernateCore_Web_Spring_Centric</class>
		<persistence>hibernateCore</persistence>
		<logic>spring</logic>
		<view>icefaces</view>
		<description></description>
	</generator>
	
	<generator>
		<name>ZathuraJavaEE_GWT_Centric</name>
		<gui-name>GWT + JPA</gui-name>
		<class>co.edu.usbcali.lidis.zathura.generator.jee.jpa.gwtcentric.engine.ZathuraJavaEE_Gwt_Centric</class>
		<persistence>jpa</persistence>
		<logic>pojo</logic>
		<view>gwt</view>
		<description></description>
	</generator>
	
</zathura-generator>
